project:
  type: website
  output-dir: docs

website:
  title: "Happy Birthday Propa Apu! 🎉"
  site-url: https://isfarbaset.github.io/propa-bday/

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    page-layout: full
    anchor-sections: false
    smooth-scroll: true
    include-in-header:
      - text: |
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    include-after-body:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/party-js@latest/bundle/party.min.js"></script>



